language: go

go:
  - 1.8.x

install: pwd

script: 
  - go run build/validate/validate.go
  - go test ./...

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always